[package]
name = "dstopic-command"
version = "0.1.0"
authors = ["Kat March√°n <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
anyhow = "1.0.24"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
